name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/search-service/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/search-service/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Quality (backend/search-service)
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      MAVEN_OPTS: -Xmx1g
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build & unit tests
        working-directory: backend/search-service
        run: ./mvnw -B -q -DskipITs=true clean verify

      - name: SpotBugs
        working-directory: backend/search-service
        run: ./mvnw -B -q spotbugs:check

      - name: Checkstyle
        working-directory: backend/search-service
        run: ./mvnw -B -q checkstyle:check

      - name: Dependency Vulnerability Scan (OWASP)
        if: ${{ github.event_name == 'push' }}
        working-directory: backend/search-service
        run: ./mvnw -B org.owasp:dependency-check-maven:check -Dformat=HTML -DfailBuildOnCVSS=7.0

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-reports
          path: |
            backend/search-service/target/surefire-reports/**
            backend/search-service/target/site/checkstyle.html
            backend/search-service/target/spotbugsXml.xml
            backend/search-service/target/dependency-check-report.html
          if-no-files-found: ignore
