name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/search-service/**'
      - 'infra/ecs-task/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/search-service/**'
      - 'infra/ecs-task/**'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Quality (backend/search-service)
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      MAVEN_OPTS: -Xmx1g

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Cache the large NVD database used by OWASP Dep Check
      - name: Cache OWASP Dependency-Check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-${{ runner.os }}-v1

      # Single run: tests + coverage + checkstyle + spotbugs + owasp via dev-quality
      - name: Build + Quality (dev-quality profile)
        working-directory: backend/search-service
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}   # optional but recommended
        run: |
          ./mvnw -B -Pdev-quality -DskipITs=true \
            -DnvdApiKey="$NVD_API_KEY" \
            -Danalyzers.assembly.enabled=false \
            -Danalyzers.retirejs.enabled=false \
            -Danalyzers.node.enabled=false \
            -Danalyzers.nugetconf.enabled=false \
            -Danalyzers.assembly.enabled=false \
            -Danalyzers.nuspec.enabled=false \
            -Danalyzers.cocoapods.enabled=false \
            -Danalyzers.swift.enabled=false \
            -Danalyzers.rubygems.enabled=false \
            -Danalyzers.python.enabled=false \
            -Danalyzers.php.enabled=false \
            clean verify
      # Generate Checkstyle HTML report (in addition to XML)
      - name: Generate site reports (Checkstyle HTML)
        working-directory: backend/search-service
        run: ./mvnw -B -Pdev-quality -DskipITs=true site

      - name: SonarCloud Scan
        working-directory: backend/search-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw -B -Pdev-quality clean verify sonar:sonar \
            -Dsonar.projectKey=com.aiproductsearch:search-service \
            -Dsonar.organization=siva-teja-singam-setty \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      # Upload key reports for quick inspection
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-reports
          path: |
            backend/search-service/target/surefire-reports/**
            backend/search-service/target/site/jacoco/index.html
            backend/search-service/target/site/checkstyle.html
            backend/search-service/target/spotbugsXml.xml
            backend/search-service/target/dependency-check-report.html
          if-no-files-found: ignore